apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-ingress
  namespace: argocd
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: dev-argo-cd.dhakkan.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port: 
              number: 80